---
- name: Check if osd_devices attribute exists
  tags: osd
  shell: "{{knife_command}} search node \"name:{{item}}\" -a ceph.osd_devices | grep {{disk}}"
  with_items: groups.ceph
  register: result
  ignore_errors: True

- name: Create osd_devices attribute
  tags: osd
  command: "{{knife_command}} exec -E \"@n=Chef::Node.load('{{item}}') ; a=@n.normal ; a['ceph']['osd_devices']=[{'device' => '{{disk}}', 'type' => 'directory'}];;@n.save\""
  with_items: groups.ceph
  when: result|failed and not "/dev/" in disk
  delegate_to: chef[0]

- name: Add OSD role
  tags: osd
  command: "{{knife_command}} node run_list add {{item}} role[ceph-osd]"
  with_items: groups.ceph

- name: Add ceph-mon role to openstack AIO node
  tags: mon
  command: "{{knife_command}} node run_list add {{groups.openstack[0]}} role[ceph-mon]"

- name: Wait for Solr cache (if we deploy OSD before cache updates from ceph-mon run then OSD deployment will fail)
  command: "{{knife_command}} exec -E \"nodes.search('role:ceph-mon AND ceph_bootstrap_osd_key:*') {|n| puts n.name}\""
  register: output
  until: output.stdout != ""
  retries: 24
  delay: 5
  changed_when: output.stdout != ""

- name: Run chef-client
  command: chef-client

- name: Run ceph-disk-active
  tags: osd
  command: "/usr/sbin/ceph-disk-activate {{disk}}"
  # Should be safe to run this on an already activated disk
  #when: "'/dev/' in disk"

- name: Run chef-client again
  tags: osd
  command: chef-client

