- name: Add single-controller, cinder-volume roles
  command: "{{knife_command}} node run_list add {{inventory_hostname}} role[single-controller],role[cinder-volume]"
  delegate_to: "{{groups.chef[0]}}"

- name: Run chef-client to deploy single-controller and cinder-volume roles.
  command: chef-client

- name: Add single-compute roles (this needs to be done after single-controller/cinder-volume are provisioned)
  command: "{{knife_command}} node run_list add {{inventory_hostname}} role[single-compute],recipe[exerstack]"
  delegate_to: "{{groups.chef[0]}}"

- name: Run chef-client to finish openstack deploy
  command: chef-client

- name: "Install cinder-volume packages."
  apt: pkg="{{item}}"
  with_items: cinder_volume_packages

