---
- name: Check if osd_devices attribute exists
  shell: "{{knife_command}} search node \"name:{{item}}\" -a ceph.osd_devices | grep {{disk}}"
  with_items: groups.ceph
  register: result
  ignore_errors: True

- name: Create osd_devices attribute
  command: "{{knife_command}} exec -E \"@n=Chef::Node.load('{{item}}') ; a=@n.normal ; a['ceph']['osd_devices']=[{'device' => '{{disk}}'}];;@n.save\""
  with_items: groups.ceph
  when: result|failed and "/dev/" in disk

- name: Create osd_devices attribute
  command: "{{knife_command}} exec -E \"@n=Chef::Node.load('{{item}}') ; a=@n.normal ; a['ceph']['osd_devices']=[{'device' => '{{disk}}', 'type' => 'directory'}];;@n.save\""
  with_items: groups.ceph
  when: result|failed and not "/dev/" in disk

- name: Add ceph-mon role to openstack AIO node
  command: "{{knife_command}} node run_list add {{groups.openstack[0]}} role[ceph-mon]"

- name: Run chef-client
  command: chef-client
